ENV_FILE="./.env"
WORLD_ADDRESS="0x8a791620dd6260079bf849dc5567adc3f2fdc318"
CHAIN_ID="31337"

#Colours
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[0m"

sed -i "s/^WORLD_ADDRESS=.*/WORLD_ADDRESS=$WORLD_ADDRESS #Local World Address/" "$ENV_FILE"
sed -i "s/^CHAIN_ID=.*/CHAIN_ID=$CHAIN_ID #Local Chain ID/" "$ENV_FILE"

printf "${GREEN}[COMPLETED]${RESET} Set ${YELLOW}WORLD_ADDRESS${RESET} in ${YELLOW}.env${RESET} to default ${YELLOW}Local${RESET} world address ${YELLOW}[$WORLD_ADDRESS]${RESET} \n\n"